(EJ2-834303): Added new samples for chart and stockchart.
syncfusion-content/ej2-charts-docs pull request #10
Opened 2023-06-21 10:44 UTC by Soundeswari-Selvam

**Description:**

Added UG for the volume 2 release features and improvement in Chart and Stock Chart.

2023-06-21 10:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-834303-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/7/)<br/>**

2023-06-21 10:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-834303-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/8/console)**

2023-06-21 10:52 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-834303-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/8/)<br/>**

2023-06-21 11:01 UTC, Gowrimathi requested changes
Requested review changes

2023-06-21 11:01 UTC, Gowrimathi commented on ej2-javascript/chart/chart-appearance.md
> +By using the `position` property, you can position the `title` at left, right, top or bottom of the chart. The title is positioned at the top of the chart, by default.
By using the `position` property in `titleStyle`, you can position the `title` at left

2023-06-21 11:23 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-834303-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/9/console)**

2023-06-21 11:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-834303-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/9/)<br/>**

2023-06-22 06:18 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-834303-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/11/console)**

2023-06-22 06:19 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-834303-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/11/)<br/>**

2023-06-22 06:52 UTC, harivenkateshe commented on ej2-javascript/chart/Chart-types/pare-to.md
> +The pareto line series can be customized by using the [`marker`](../api/chart/paretoOptions/#marker), [`width`](../api/chart/paretoOptions/#width), [`dashArray`](../api/chart/paretoOptions/#dasharray
For the "paretoOptions", API reference link is missing.

2023-06-22 07:16 UTC, harivenkateshe commented on ej2-javascript/stock-chart/tool-tip.md
> +By using the [`position`](../api/stock-chart/stockTooltipSettings/#position) property, you can fix the tooltip in one position or have it move along with the mouse. By default, the tooltip is positio
Check and correct this sentence - "By default, the tooltip is positioned at the left of the stock chart."

2023-06-22 07:25 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-834303-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/12/)<br/>**

2023-06-22 07:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-834303-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/13/console)**

2023-06-22 07:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-834303-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/13/)<br/>**

2023-06-22 07:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-834303-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/14/console)**

2023-06-22 07:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-834303-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/14/)<br/>**

2023-06-22 07:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-834303-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/15/)<br/>**

2023-06-22 08:06 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-834303-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/16/)<br/>**

2023-06-22 09:26 UTC, Gowrimathi approved these changes
Fine

2023-06-23 05:28 UTC, merged