(EJ2-845677): Added Volume 3 features samples in TS and JS UG.
syncfusion-content/ej2-charts-docs pull request #26
Opened 2023-09-12 08:54 UTC by Soundeswari-Selvam

**Description:**

Added Volume 3 features sample.

2023-09-12 09:01 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/29/console)**

2023-09-12 09:02 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/29/)<br/>**

2023-09-12 09:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/30/console)**

2023-09-12 09:06 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/30/)<br/>**

2023-09-12 09:08 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/31/)<br/>**

2023-09-12 10:20 UTC, Gowrimathi requested changes
Requested changes

2023-09-12 10:20 UTC, Gowrimathi commented on ej2-javascript/chart/chart-print.md
> +You can customize text, page number, line, page size and changing orientation in header and footer.
The PDF export option allows you to include a header and footer in the exported chart, where you can add text.

2023-09-12 10:20 UTC, Gowrimathi commented on ej2-javascript/chart/chart-print.md
> +You can export the multiple charts in multiple page by passing the multiple chart objects in the export method of chart.
You can export charts from the web page onto multiple pages within a PDF document.

2023-09-12 10:20 UTC, Gowrimathi commented on ej2-javascript/chart/synchronized-chart.md
> +{% if page.publishingplatform == "typescript" %}
This is not all what we discussed. We need to explain about how to synchronize tooltip, crosshair, zooming and selection.

2023-09-12 11:13 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/32/)<br/>**

2023-09-12 11:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/33/)<br/>**

2023-09-12 11:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/34/)<br/>**

2023-09-13 05:46 UTC, Gowrimathi requested changes
Requested changes

2023-09-13 05:46 UTC, Gowrimathi commented on ej2-javascript/chart/chart-print.md
> +The PDF export option allows you to include a header and footer in the exported chart, where you can add text.
In the export method, specify the following parameters to add a header and footer to the exported PDF document:

2023-09-13 05:46 UTC, Gowrimathi commented on ej2-javascript/chart/chart-print.md
> +The rendered chart can be exported to `XLSX` or `CSV` format using the excel export method in chart. The input parameters for this method are `Export Type` for format and `fileName` for result.
You can export the rendered chart data to XLSX or CSV formats using the export method.

In the export method, you'll need to specify the following parameters in order to export the data to Excel:

2023-09-13 05:46 UTC, Gowrimathi commented on ej2-javascript/chart/chart-print.md
> +You can export charts from the web page onto multiple pages within a PDF document.
In the export method, specify the following parameter to export charts to multiple pages in a PDF format.

2023-09-13 06:13 UTC, Gowrimathi requested changes
Requested added

2023-09-13 06:13 UTC, Gowrimathi commented on ej2-javascript/chart/synchronized-chart.md
> +Tooltip synchronization enhances the data visualization experience by seamlessly coordinating tooltips across multiple charts. When we hover over a data point in one chart, synchronized tooltips inte
Synchronize the tooltips across the multiple charts using 'showTooltip' and 'hideTooltip' methods. When we hover over a data point in one chart, call the showTooltip method for the rest of the chart to display related information in other connected charts simultaneously.

In the showTooltip method, specify the following parameter programmatically to enable tooltips for a particular chart:

'x' - Data point x-value or x-coordinate value.
'y' - Data point y-value or y-coordinate value.

2023-09-13 06:13 UTC, Gowrimathi commented on ej2-javascript/chart/synchronized-chart.md
> +Crosshair synchronization ensures that as we navigate one chart, the crosshair cursor precisely aligns with data points in other linked charts, simplifying data comparison and analysis.
Synchronize the crosshair across multiple charts using the 'showCrosshair' and 'hideCrosshair' methods. When hovering over one chart, call the 'showCrosshair' method for the rest of the charts to align with data points in other linked charts, simplifying data comparison and analysis.

In the 'showCrosshair' method, specify the following parameter programmatically to enable crosshairs for a particular chart:

'x' - Specifies the x value of the point or x-coordinate.
'y' - Specifies the y value of the point or y-coordinate.

2023-09-13 06:13 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/35/)<br/>**

2023-09-13 06:36 UTC, Gowrimathi requested changes
Requested changes

2023-09-13 06:36 UTC, Gowrimathi commented on ej2-javascript/chart/synchronized-chart.md
> +Zoom synchronization ensures coherence across multiple charts by maintaining consistent zoom levels. It delivers a unified perspective of  data, facilitating comprehensive analysis at various levels
You can maintain consistent zoom levels across multiple charts using the `zoomComplete` event. In the zoomComplete event, obtain the `zoomFactor` and `zoomPosition` values of the particular chart and then apply the same values to the rest of the charts.

2023-09-13 06:36 UTC, Gowrimathi commented on ej2-javascript/chart/synchronized-chart.md
> +Selection synchronization streamlines data analysis by highlighting related data points in all connected charts when we make a selection, enabling seamless comparison.
You can select the data across multiple charts using the `selectionComplete` event. In the selectionComplete event, obtain the selected values of the current chart and then apply the same values to the rest of the charts.

2023-09-13 07:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/36/console)**

2023-09-13 07:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/36/)<br/>**

2023-09-13 09:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/37/)<br/>**

2023-09-13 10:11 UTC, Gowrimathi requested changes
Requested changes

2023-09-13 10:11 UTC, Gowrimathi commented on ej2-javascript/chart/chart-print.md
> +* `header` - In the header, we can specify the text that is to appear at the top of the exported PDF.
Specify the text that should appear at the top of the exported PDF.
Specify the text that should appear at the Bottom of the exported PDF.

2023-09-13 10:11 UTC, Gowrimathi commented on ej2-javascript/chart/chart-print.md
> +* `fileName` - You can specify a name for the exported documents.
Specify the export format as either 'XLSX' or 'CSV' for exporting in Excel.
A name for the exported file.

2023-09-13 10:11 UTC, Gowrimathi commented on ej2-javascript/chart/chart-print.md
> +* `exportToMultiplePage` - You can enable `exportToMultiplePage` to export each chart on an individual page.
Set 'exportToMultiplePage' to true in order to export each chart on an individual page.

2023-09-13 10:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/38/console)**

2023-09-13 10:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/38/)<br/>**

2023-09-13 10:25 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/39/console)**

2023-09-13 10:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/39/)<br/>**

2023-09-13 10:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/40/console)**

2023-09-13 10:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/40/)<br/>**

2023-09-13 13:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/41/)<br/>**

2023-09-14 06:49 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/42/console)**

2023-09-14 06:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/42/)<br/>**

2023-09-14 11:29 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/43/console)**

2023-09-14 12:17 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/43/console)**

2023-09-14 12:22 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/43/)<br/>**

2023-09-14 17:51 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/44/console)**

2023-09-14 18:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/44/console)**

2023-09-14 18:12 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/44/)<br/>**

2023-09-15 04:12 UTC, Gowrimathi approved these changes
Fine

2023-09-15 04:12 UTC, Gowrimathi commented on ej2-javascript/chart/chart-print.md
> +During the PDF export, you can export each chart as a separate page by setting the `exportToMultiplePage` parameter to **true**.
During PDF export, set the exportToMultiplePage parameter to true to export each chart as a separate page.

2023-09-15 05:46 UTC, Gowrimathi approved these changes
Fine

2023-09-17 06:51 UTC, Soundeswari-Selvam commented
rebuild

2023-09-19 05:02 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/45/console)**

2023-09-19 05:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/45/console)**

2023-09-19 05:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-845677-newSamples](https://jenkins.syncfusion.com/job/Content/job/ej2-charts-docs/45/)<br/>**

2023-09-19 05:13 UTC, merged